table Subscription
	lineageTag: 5f81b557-4af8-44b7-a1bd-26dbe789f466

	measure 'Avg cost Week' = AVERAGEX(VALUES('Subscription'[WeekNumber]),CALCULATE(SUM('Subscription'[CostUSD])))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d52065b8-d8e9-4125-aa88-206fc96334ff

	measure 'Avg cost Month' = AVERAGEX(VALUES('Subscription'[Month]),CALCULATE(SUM('Subscription'[CostUSD])))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ebaaa3cb-bea2-4193-b167-3b11b14bf4a4

	measure 'Avg cost Year' = AVERAGEX(VALUES('Subscription'[Year]),CALCULATE(SUM('Subscription'[CostUSD])))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 28e40a8e-588d-466d-9305-c60ab8274df9

	column Year
		dataType: string
		lineageTag: b912597e-575f-47dc-8c45-3cb0f046dfdd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 17ddca34-9d35-4199-898a-50ed9fec1ab2
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column WeekNumber
		dataType: string
		lineageTag: 697756b3-140e-4898-bf69-714d0caa9570
		summarizeBy: none
		sourceColumn: WeekNumber

		annotation SummarizationSetBy = Automatic

	column Subscription
		dataType: string
		lineageTag: 33473af3-d6ed-43f9-9c2f-2554b7804934
		summarizeBy: none
		sourceColumn: Subscription

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: string
		lineageTag: eb732cfc-b971-4b3f-829c-0bb9a008090b
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column 'Resource Name'
		dataType: string
		lineageTag: 17f89ba4-d4e5-4a12-9413-ebc3efb3c0c8
		summarizeBy: none
		sourceColumn: Resource Name

		annotation SummarizationSetBy = Automatic

	column ResourceType
		dataType: string
		lineageTag: 2f1f343c-7f8a-41bb-9ac2-f2b9f237e7cd
		summarizeBy: none
		sourceColumn: ResourceType

		annotation SummarizationSetBy = Automatic

	column ResourceLocation
		dataType: string
		lineageTag: d3734951-c517-4f7b-87b7-bb370eb6a2ae
		summarizeBy: none
		sourceColumn: ResourceLocation

		annotation SummarizationSetBy = Automatic

	column ResourceGroupName
		dataType: string
		lineageTag: 93d17f96-934a-485e-a141-3c623d66338e
		summarizeBy: none
		sourceColumn: ResourceGroupName

		annotation SummarizationSetBy = Automatic

	column ServiceName
		dataType: string
		lineageTag: 335a4405-c5f9-4c27-b87a-0757cc551fa3
		summarizeBy: none
		sourceColumn: ServiceName

		annotation SummarizationSetBy = Automatic

	column Meter
		dataType: string
		lineageTag: fe6955d7-06fc-44d2-85de-da367ca4560a
		summarizeBy: none
		sourceColumn: Meter

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 454efb83-ab10-4470-9706-e3ea5d984adb
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column CostUSD
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 74e0bc39-437a-4690-80e3-bbc5ad312dd4
		summarizeBy: sum
		sourceColumn: CostUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Cost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6185d650-4c47-4334-9fef-d1337b58dae2
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: fc141f0c-596c-4db1-9bfe-2086e1a8cbfb
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column MonthNumber = ```
			SWITCH(
			    TRUE(),
			    'Subscription'[Month] = "January", 1,
			    'Subscription'[Month] = "February", 2,
			    'Subscription'[Month] = "March", 3,
			    'Subscription'[Month] = "April", 4,
			    'Subscription'[Month] = "May", 5,
			    'Subscription'[Month] = "June", 6,
			    'Subscription'[Month] = "July", 7,
			    'Subscription'[Month] = "August", 8,
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: fe5ba235-6b39-49a5-abb4-20a9935c00df
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'IT Owner Tag'
		dataType: string
		lineageTag: 189facfb-c742-428f-8196-81146fbe9717
		summarizeBy: none
		sourceColumn: IT Owner Tag

		annotation SummarizationSetBy = Automatic

	column 'Environment Tag'
		dataType: string
		lineageTag: 600a412c-f87a-4166-9184-e503f85e4be5
		summarizeBy: none
		sourceColumn: Environment Tag

		annotation SummarizationSetBy = Automatic

	column 'IT Administrator Tag'
		dataType: string
		lineageTag: 4e355e08-01e8-4ec6-8514-16d984bb6bb4
		summarizeBy: none
		sourceColumn: IT Administrator Tag

		annotation SummarizationSetBy = Automatic

	column 'Created By Tag'
		dataType: string
		lineageTag: b4039c5e-c0c2-4c30-a022-19abe826f587
		summarizeBy: none
		sourceColumn: Created By Tag

		annotation SummarizationSetBy = Automatic

	column 'App Name Tag'
		dataType: string
		lineageTag: fb9b10d6-ecb8-4ebc-852d-007fc0953b4e
		summarizeBy: none
		sourceColumn: App Name Tag

		annotation SummarizationSetBy = Automatic

	column CurrentWeek = IF(Subscription[WeekNum] = WEEKNUM(TODAY()), 1, 0)
		formatString: 0
		lineageTag: 4bd7ff76-e2ba-4ee5-a4ee-7a82756ff584
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column WeekNum
		dataType: int64
		formatString: 0
		lineageTag: 4c4751b7-2161-4dd1-9a2e-972fbf6650f7
		summarizeBy: sum
		sourceColumn: WeekNum

		annotation SummarizationSetBy = Automatic

	column PreviousWeek = ```
			IF(Subscription[WeekNum] = WEEKNUM(TODAY()) - 1, 1, 0)
			
			```
		formatString: 0
		lineageTag: d315847c-e0ac-46f5-85aa-3c19832da747
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Subscription = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://techstarconsultinginc-my.sharepoint.com/personal/poojabaskar_techstargroup_com/Documents/DESKTOP/PROJECTS/Roots/Cost%20Analysis%20BI%20Data/Cost_Management_Master_Sheet.xlsx"), null, true),
				    #"Dev- subscription_Sheet" = Source{[Item="Dev- subscription",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dev- subscription_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"Month", type text}, {"Week Number", type text}, {"Subscription", type text}, {"ResourceId", type text}, {"Resource Name", type text}, {"ResourceType", type text}, {"ResourceLocation", type text}, {"ResourceGroupName", type text}, {"ServiceName", type text}, {"Meter", type text}, {"Tags", type text}, {"CostUSD", type number}, {"Cost", type number}, {"Currency", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Week Number", "WeekNumber"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", #"Prod- Subscription"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Appended Query","","Untagged",Replacer.ReplaceValue,{"Tags"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Year", type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type1"," mahesh salem","mahesh salem",Replacer.ReplaceText,{"IT Owner Tag"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value1", "WeekNumber", "WeekNumber - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"WeekNumber - Copy", "WeekNum"}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1","Week","",Replacer.ReplaceText,{"WeekNum"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value2",{{"WeekNum", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

